// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _01_ProductCatalog.MVC.Data;

#nullable disable

namespace _01_ProductCatalog.MVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619043517_SeedSampleSellers")]
    partial class SeedSampleSellers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("KeywordProduct", b =>
                {
                    b.Property<string>("KeywordsName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductsId")
                        .HasColumnType("TEXT");

                    b.HasKey("KeywordsName", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("KeywordProduct");
                });

            modelBuilder.Entity("_01_ProductCatalog.MVC.Models.Category", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Category_Name");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("Category_Creation_Time");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Category_Shop_Id");

                    b.HasKey("Name");

                    b.HasIndex("ShopId");

                    b.ToTable("Shop_Categories");
                });

            modelBuilder.Entity("_01_ProductCatalog.MVC.Models.Keyword", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Keyword_Name");

                    b.HasKey("Name");

                    b.ToTable("Product_Keywords");
                });

            modelBuilder.Entity("_01_ProductCatalog.MVC.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Product_Id");

                    b.Property<int>("AvailableStock")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Product_Available_Stock");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT")
                        .HasColumnName("Product_Category_Name");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("Product_Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Product_Name");

                    b.Property<DateTime>("PostedTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("Product_Posted_Time");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("Product_Profile_Picture");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Product_Shop_Id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName");

                    b.HasIndex("ShopId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("_01_ProductCatalog.MVC.Models.Seller", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Shop_Id");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("Seller_Bio");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT")
                        .HasColumnName("Date_Of_Birth");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Seller_Name");

                    b.Property<DateTime>("ProfileCreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("Profile_Creation_Time");

                    b.HasKey("Id");

                    b.ToTable("Shop_Sellers");

                    b.HasData(
                        new
                        {
                            Id = "019ede29-6976-7f78-9a60-60a851dc132d",
                            Bio = "It's a simple bio!",
                            DateOfBirth = new DateTime(2002, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hasib Hasnain",
                            ProfileCreationTime = new DateTime(2026, 6, 19, 4, 35, 16, 471, DateTimeKind.Utc).AddTicks(5021)
                        },
                        new
                        {
                            Id = "019ede29-6977-7506-9e28-5467d58a5890",
                            Bio = "Honest and Elegent Seller!",
                            DateOfBirth = new DateTime(2000, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rahim Iqbal",
                            ProfileCreationTime = new DateTime(2026, 6, 19, 4, 35, 16, 471, DateTimeKind.Utc).AddTicks(7576)
                        },
                        new
                        {
                            Id = "019ede29-6977-7c31-8c79-b2b0b197832b",
                            Bio = "Selling My Used Bat Balls!",
                            DateOfBirth = new DateTime(1997, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tamim Iqbal",
                            ProfileCreationTime = new DateTime(2026, 6, 19, 4, 35, 16, 471, DateTimeKind.Utc).AddTicks(7606)
                        });
                });

            modelBuilder.Entity("_01_ProductCatalog.MVC.Models.Shop", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Shop_Id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("Creation_Time");

                    b.Property<string>("OwnerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Shop_Owner_Id");

                    b.Property<string>("ShopDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Shop_Description");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Shop_Name");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("KeywordProduct", b =>
                {
                    b.HasOne("_01_ProductCatalog.MVC.Models.Keyword", null)
                        .WithMany()
                        .HasForeignKey("KeywordsName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_01_ProductCatalog.MVC.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_01_ProductCatalog.MVC.Models.Category", b =>
                {
                    b.HasOne("_01_ProductCatalog.MVC.Models.Shop", "Shop")
                        .WithMany("Categories")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("_01_ProductCatalog.MVC.Models.Product", b =>
                {
                    b.HasOne("_01_ProductCatalog.MVC.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryName");

                    b.HasOne("_01_ProductCatalog.MVC.Models.Shop", "Shop")
                        .WithMany("Products")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("_01_ProductCatalog.MVC.Models.Shop", b =>
                {
                    b.HasOne("_01_ProductCatalog.MVC.Models.Seller", "Owner")
                        .WithMany("OwnedShops")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("_01_ProductCatalog.MVC.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("_01_ProductCatalog.MVC.Models.Seller", b =>
                {
                    b.Navigation("OwnedShops");
                });

            modelBuilder.Entity("_01_ProductCatalog.MVC.Models.Shop", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
